version: "3"
services:
  server:
    build: "."
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_HOST=db
      - PORT=8000
      - SERVER_PRIVATEKEY=${SERVER_PRIVATEKEY}
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - 5434:5432
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
